### ISSUE TITLE
Unable to compile on AVR MEGA 2560 (V10.0.0-3)

### ISSUE THREAD

**Issue by lazarus-long** [feilipu/avrfreertos#5]
When compiling the AnalogRead_DigitalRead demo project on Arduino MEGA 2560 with version 10.0.0-3 I get the following error:

Arduino: 1.8.5 (Windows 7), Board: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

Build options changed, rebuilding all
C:\Users\a35963q\AppData\Local\Temp\cczKcV5x.ltrans1.ltrans.o: In function `main':

cczKcV5x.ltrans1.o:(.text.startup+0x262): undefined reference to `\_\_EIND\_\_'

C:\Users\a35963q\AppData\Local\Temp\cczKcV5x.ltrans0.ltrans.o: In function `vPortYieldFromTick':

cczKcV5x.ltrans0.o:(.text.hot+0x20): undefined reference to `\_\_EIND\_\_'

cczKcV5x.ltrans0.o:(.text.hot+0x39a): undefined reference to `\_\_EIND\_\_'

C:\Users\a35963q\AppData\Local\Temp\cczKcV5x.ltrans0.ltrans.o: In function `vPortYield':

cczKcV5x.ltrans0.o:(.text.hot+0x5ca): undefined reference to `\_\_EIND\_\_'

cczKcV5x.ltrans0.o:(.text.hot+0x73a): undefined reference to '\_\_EIND\_\_'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

With version 10.0.0.-1 there are no errors.

**Comment by FrozenDroid** [comment]
+1 Can confirm this

**Comment by FrozenDroid** [comment]
@feilipu Mind looking at this?

**Comment by feilipu** [comment]
This issue affects Arduno_FreeRTOS_Library. Not this repository.

I’ll take a look there.

**Comment by FrozenDroid** [comment]
No, it also affects this repo. Couldn't compile it with avr-gcc.

**Comment by feilipu** [comment]
Ok sorry. The original issue comment was directed to Arduino_FreeRTOS_Library. But, you are correct that the issue is propagated here too. 

I converted the calls to register 3C to refer to `__EIND__`  (and also `__RAMPZ__` from 3B) Possibly, there is an include file reference missing, but afk now. Will solve this on weekend.

**Comment by feilipu** [comment]
OK. I can not confirm this issue on Ubuntu 16.04 either using the standard avr-gcc anf avr-libc, or using Arduino 1.8.5.

The `__EIND__` variable is defined by the [`avr/io.h`](http://www.atmel.com/webdoc/avrlibcreferencemanual/group__avr__io.html) set of files.

This is automatically included by the [`#include <avr/interrupt.h>`](http://www.atmel.com/webdoc/avrlibcreferencemanual/group__avr__interrupts.html) reference included in the [`port.c`](https://github.com/feilipu/avrfreertos/blob/master/freeRTOS10xx/portable/port.c#L31) file. The file which actually contains the references to `__EIND__`.

So, provided you're correctly setting up your Eclipse environment (for ATmega250 MCU type) the required compile defines should be made to allow the correct `avr/io.h` to be included, providing the `__EIND__` defines.

**Comment by FrozenDroid** [comment]
I can't find `__EIND__` anywhere. What avr-gcc and avr-libc are you using? I got avr-gcc 7.2.0. I'm not using Eclipse, I'm using CLion with a CMakeLists template.

**Comment by feilipu** [comment]
`__EIND__` is [defined in avr-gcc](https://gcc.gnu.org/ml/gcc-patches/2011-10/msg01945.html), but doesn't seem to available to every linker. I've added a [safety net definition](https://github.com/feilipu/avrfreertos/commit/a0a1402233bc3fd2bef7d3cfd0e05e1d99268390) of  both `__RAMPZ__` and `__EIND__` to avoid further issues.

**Comment by FrozenDroid** [comment]
Awesome! Didn't test it myself but I'm sure that solves it. Cheers!

**Comment by feilipu** [comment]
Yep. But, nope. I had to move the definitions. 

Providing the definitions in the `port.c` file doesn't allow the macro to be used in other files.
So, I had to [move the definitions to `portmacro.h`](https://github.com/feilipu/avrfreertos/commit/405153d90f63b1f5f53a355cfa2ee7241e586e9a).

The new release is `10.0.0-5` Update your libraries, and give it a try in 60 minutes.

**Comment by mjuels** [comment]
I have the same issue still in version 10.0.0-5, both in Arduino IDE (1.8.5) as well as in eclipse.
The issue seems to be limited to Mega, i.e. Uno compiles with no issues.
The issue is resolved by downgrading to 10.0.0-1

**Comment by feilipu** [comment]
Fixed with 10.0.0-6.

The issue was (is) that a #define for `__EIND__` was not being expanded. I had tried to prettify the macro, but now it is back to being `0x3C`... oh well.

**Comment by mjuels** [comment]
Thnx, that did it :-) :+1:
